export const ACTION_TYPES = {
    FETCH_COURSES: 'FETCH_COURSES',
    FETCH_AUTHORS: 'FETCH_AUTHORS',
    ADD_COURSE: 'ADD_COURSE',
    EDIT_COURSE: 'EDIT_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    ADD_AUTHOR: 'ADD_AUTHOR',
    ADD_COURSE_LOADING: 'ADD_COURSE_LOADING',
    ADD_COURSE_COMPLETED: 'ADD_COURSE_COMPLETED'
}